### ISSUE TITLE
404 on /feedbacks api call

### ISSUE THREAD

**Issue by rocramer** [mydnic/nova-kustomer#1]
Hey Clément,

really nice feedback component, thanks! :slightly_smiling_face: 

I installed the nova tool and tried to open it but it doesn't load properly. I always get a 404 on the following api call: http://localhost:8000/nova-vendor/nova-kustomer/feedbacks

Am I doing something wrong?

Thanks,
Robin

**Comment by mydnic** [comment]
That's really weird.. Is there any other Nova tool working beside nova-kustomer ?

You can maybe try to clear the cache or route cache ?

**Comment by rocramer** [comment]
Clear the routes cache helped.

Strangely I had never to do this before. All other (and own) tools worked without clearing.

**Comment by mydnic** [comment]
@rocramer maybe one of those tools have caches the routes some point ? Because normally the routes are never cached automatically, and I never had to do that either... I'll check a few other nova tools how they are configured
